### ISSUE TITLE
1.17.1 build?

### ISSUE THREAD

**Issue by vos6434** [PTOM76/PipePlus#1]
why go back a version? simple pipes is out for 1.17.

**Comment by PTOM76** [comment]
シンプルパイプはベータ版なので、とりあえず1.16.5で開発しました。次回は1.17, 1.17.1でリリースされるかもしれません。

**Comment by PTOM76** [comment]
Since simple pipes is a beta version, I developed it with 1.16.5 for the time being. Maybe It will be released 1.17 next time.

**Comment by PTOM76** [comment]
The 1.17.1 version has also been released.
https://www.curseforge.com/minecraft/mc-mods/pipeplus/files/3425912
