### ISSUE TITLE
Pipes not functioning Tech Reborn

### ISSUE THREAD

**Issue by xanthian** [PTOM76/PipePlus#10]
Are they meant to work with Tech Reborn ?

I'm trying to move items from 1 machine to another
but the pipes dont even connect to the blocks
![image](https://user-images.githubusercontent.com/7688001/140929277-ba19faee-c25b-41d9-989e-165f20535552.png)

**Comment by PTOM76** [comment]
Have you set up TechReborn machine slots?
Then if you break pipe and place pipe, it will be fixed.

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/141118311-9177822e-12c0-476f-84dd-be2713ed6b6d.png)
![image](https://user-images.githubusercontent.com/7688001/141118345-965a9860-1629-4b4f-bc70-1adb1b738e86.png)

Nope?

**Comment by PTOM76** [comment]
There is an item pipe in the item slot.

**Comment by xanthian** [comment]
> There is an item pipe in the item slot.

?
