### ISSUE TITLE
Is this supposed to happen? I don't see why this would be caused by another mod.

### ISSUE THREAD

**Issue by HacoKavanah** [PTOM76/PipePlus#11]
![image](https://user-images.githubusercontent.com/87395651/161599533-ab0dae8b-1711-4c2b-acfd-6cf6a7a541c7.png)

**Comment by PTOM76** [comment]
This is a bug caused by using a non-existent tag in a recipe.
Thank you for your report.

**Comment by PTOM76** [comment]
However, I want to keep it for MOD compatibility, so I will not deal with it here.
If you want to solve this, open the jar with 7zip etc. and delete "data/pipeplus/recipes/crafting/pipe_items_teleport.json".
