### ISSUE TITLE
The game throws an error when attaching any facade to a pipe

### ISSUE THREAD

**Issue by Kamikamiku** [PTOM76/PipePlus#12]
The game threw an error when I tried to add a facade to the pipe and kicked me out of the single player game, here's a screenshot.
![2022-04-13](https://user-images.githubusercontent.com/67572116/163021526-cb2788ea-d5d2-4fdd-ac50-922381455125.png)
How to reproduce:
1. Place any pipe from plpeplus.
2. Attach any facade to this pipe.
3. Game freezes and throws an error

This is the game log:
[2022-4-13.log](https://github.com/PTOM76/PipePlus/files/8475272/2022-4-13.log)

I think this is caused by your mod, since attaching facades to pipes that from Simple BC Pipes is fine. Sorry if I'm wrong.

**Comment by Romz24** [comment]
I checked it myself, and the problem is really present.

Video: https://youtu.be/6okQCjWCCXw

**Comment by Aquaeyes** [comment]
[latest.txt](https://github.com/PTOM76/PipePlus/files/9278426/latest.txt)
Same with wired Redstone.

**Comment by PTOM76** [comment]
fixed
