### ISSUE TITLE
[Crash] Initializing game

### ISSUE THREAD

**Issue by Romz24** [PTOM76/PipePlus#13]
I installed your mod, when I try to start the game, it just crashes at the moment of initialization. I installed all the necessary dependencies, but this does not help get rid of the crash.

Mod list:
![image](https://user-images.githubusercontent.com/2458113/168790032-1bd7c53d-e7c2-4f8f-b250-b87f93f3e8f2.png)

[crash-2022-05-17_13.17.43-client.txt](https://github.com/PTOM76/PipePlus/files/8707345/crash-2022-05-17_13.17.43-client.txt)

**Comment by Romz24** [comment]
UPD: By testing, I realized that for your mod to work, you need to install [architectury-api](https://www.curseforge.com/minecraft/mc-mods/architectury-api), without it the game simply will not start.

**Comment by PTOM76** [comment]
added depends to fabric.mod.json
