### ISSUE TITLE
The specified mixin 'ml.pkom.pipeplus.mixin.RegisterSpritesMixin' was not found

### ISSUE THREAD

**Issue by lucyfoxxy** [PTOM76/PipePlus#14]
Client throws an error during startup (see errorlog).
How to fix this?

[errorlog.txt](https://github.com/PTOM76/PipePlus/files/10915575/errorlog.txt)

**Comment by PTOM76** [comment]
what's mod version?
0.5.0?

**Comment by lucyfoxxy** [comment]
yeah its PipePlus-1.19.3-0.5.0

**Comment by lucyfoxxy** [comment]
If I remove
```
  "client": [
    "RegisterSpritesMixin"
  ],
```
from your mixins.json the mod is working and everything seems to be fine for me..
But I'm no mod developer and ive no clue what this mixin usually should do

**Comment by PTOM76** [comment]
thanks for your reporting!
fixed
uploaded PipePlus-1.19.3-0.5.1
