### ISSUE TITLE
Mod suddenly stopped working

### ISSUE THREAD

**Issue by lucyfoxxy** [PTOM76/PipePlus#16]
Suddenly all Pipes from your mod aren't doing anything anymore. I cannot right-click activate them either.
The Simple BC Pipes are still working without any problems. The only thing that may have been changed was updating the dependencies the latest version for 1.19.3, 
I'm currently using these versions:
PipePlus-1.19.3-0.5.1
mcpitanlibarch-1.5.9-1.19.3-fabric
cloth-config-9.0.94-fabric
simplepipes-all-0.9.2
and additionally on the server:
libblockattributes-all-0.12.0
libmultipart-all-0.9.0
libnetworkstack-base-0.8.0
Removing and replacing the pipes does not make any difference btw. Any ideas on how to solve this? I really dont wanna only use the Simple BC Pipes

**Comment by PTOM76** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/pipeplus/files/4472651

**Comment by lucyfoxxy** [comment]
You are the best mate, thank you!
