### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by MechanosG** [PTOM76/PipePlus#18]
https://mclo.gs/gLriCG7
1.19.4 Quilt, without PipePlus present Simple Pipes works correctly.

**Comment by PTOM76** [comment]
uploaded mcpitanlib-1.6.10

**Comment by MechanosG** [comment]
Updated to MCPitanLib 1.6.10 and the problem is fixed, and I confirmed that I was able to craft a copper pipe and extract items with it.  Thank you.  :)
