### ISSUE TITLE
Changes in MCPitanLib from version 1.9.6 to 2+ causing crash.

### ISSUE THREAD

**Issue by JakeYde** [PTOM76/PipePlus#25]
Not sure what changed but when updating my instances when upgrading other mods after switching to a newer version of MCPitanLib now it's causing a crash with Pipe Plus in Minecraft with Fabric Version 1.20.1 

Disabling PipePlus fixes the instance, disabling other mods dependent on MCPitanLib and reverting to an earlier version fixes the instance.

[crash-2024-02-18_01.01.51-client.txt](https://github.com/PTOM76/PipePlus/files/14321455/crash-2024-02-18_01.01.51-client.txt)

**Comment by PTOM76** [comment]
I'm sorry, but the transition to the 2.x.x series has not yet been completed, so please use the 1.x.x series for a while.

**Comment by PTOM76** [comment]
fixed
