### ISSUE TITLE
Mod making it to where stone bricks aren't breakable with pickaxe.

### ISSUE THREAD

**Issue by JakeYde** [PTOM76/PipePlus#26]
Release version 1.20.1 
Mod Version 1.1.4
Steps to reproduce: Place stone bricks, try to harvest stone bricks with stone pickaxe or above.
Special note, with mod enabled "can I mine this block" doesn't show block as harvestable. 
![image](https://github.com/PTOM76/PipePlus/assets/1791389/8dd825ae-83ea-4ca4-afde-f34c48b15bad)
Only change, mod disabled.
![image](https://github.com/PTOM76/PipePlus/assets/1791389/87d4858f-3ee2-46ef-97b3-f9d9eccc2724)
![image](https://github.com/PTOM76/PipePlus/assets/1791389/1ea8bdf4-7425-4557-8a89-568e15089381)

**Comment by PTOM76** [comment]
Fixed. thanks for your reporting.
released 1.1.4-fix.1
