### ISSUE TITLE
teleportation pipe

### ISSUE THREAD

**Issue by zeddyccus** [PTOM76/PipePlus#3]
teleportation pipe crashes the game in version 1.17.1

**Comment by quentfr21** [comment]
hello 

for me also in 1.17.1 it's not crashing but it's not working (don't even teleport 3 block away)

thanks in advance

**Comment by PTOM76** [comment]
OK. Thank you for your report.
I checked and it didn't work on the server at all.
I'll fix it if I can, but it may be slower.

**Comment by moidu21** [comment]
i think i fix it in sp at least it's not crasing you need to test it before doing anything #4

**Comment by moidu21** [comment]
look like on server the pipe don't get the destination pipe from teleportmanager instance getconnectedpipe i try to make the server find it but for now i fail i will tell you if i find a way

**Comment by PTOM76** [comment]
The server issue has already been fixed, but I'm struggling with the issue of not being able to use it without restarting the game.
Release after fixing an issue that doesn't work after installation.

**Comment by moidu21** [comment]
can you push your work to the 1.17 branch like that i can also try with my little knownledge thanks in advance

**Comment by PTOM76** [comment]
https://github.com/PTOM76/PipePlus/tree/1.17.1
I'm suspicious of loading the PipeItemsTeleportEntity constructor and NBT.

**Comment by moidu21** [comment]
you can make a try with #5

**Comment by PTOM76** [comment]
Fixed an issue where the teleport pipe was not available on the server, the default teleport pipe was not available, and the crash for the help of moidu 21.
Both 1.17.1 and 1.16.5 will be released.
