### ISSUE TITLE
Missing recipe for Copper Transport Pipe in 0.3.1-1.17.1

### ISSUE THREAD

**Issue by Kogarou-san** [PTOM76/PipePlus#8]
It seems Copper Transport Pipe (銅パイプ) is impossible to craft due to it lacking a recipe; Roughly Enough Items can't show any way to craft it too.
This is happening in PipePlus version 0.3.1 for Minecraft 1.17.1 .
Thank you for you attention.

**Comment by PTOM76** [comment]
I forgot to register the recipe for copper ingot by 1.17.
Thank you for your report.
